# Stage 1: Build the Rust application
FROM rust:1.83-alpine3.20 AS builder

WORKDIR /app

# Install necessary dependencies for building the application
RUN apk add --no-cache \
    build-base \
    perl \
    pkgconfig \
    libffi-dev \
    musl-dev \
    musl \
    openssl-dev \
    openssl-libs-static

# Copy Cargo files and source code
COPY Cargo.toml Cargo.lock ./
COPY ./src ./src

# Build the release version of the application
RUN cargo build --release

# Stage 2: Create the minimal runtime image
FROM scratch 

WORKDIR /app

# Environment variables
ENV RUST_LOG=actix_web=debug
ENV DATABASE_URI=mongodb+srv://sriramsenthilnathan:senthil-mongodb@midgard-api.u15zb.mongodb.net/
ENV PORT=8080
ENV SECRET=testingkey
ENV WEBAUTHN_ID=main.duy9sja1w7b1i.amplifyapp.com
ENV WEBAUTHN_ORIGIN=https://main.duy9sja1w7b1i.amplifyapp.com/

# Copy the compiled binary from the builder stage
COPY --from=builder /app/target/release/server /app/my-rust-app

# Expose the port the app will listen on
EXPOSE 8080

# Command to run the application
CMD ["/app/my-rust-app"]
