import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import NavigationBar from "@/components/navigation/NavigationBarComponent";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-satoshi antialiased bg-custom-gradient">
        <NavigationBar />
        <ToastContainer className="text-xs lg:text-base md:text-base" />
        {children}
      </body>
    </html>
  );
}
